# Generated by Django 4.1 on 2022-09-25 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='f_name',
            new_name='name',
        ),
    ]
